#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

ROOT="./"

echo "php-cs pre commit hook start"

PHP_CS="vendor/bin/phpcbf"
HAS_PHP_CS=false

if [ -x vendor/bin/phpcbf ]; then
    HAS_PHP_CS=true
fi

if $HAS_PHP_CS; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        $PHP_CS --standard=$ROOT/phpcs.xml "$line";
        git add "$line";
    done
else
    echo "Please install php-cs, e.g.:"
fi

echo "php-cs pre commit hook finish"
